arti.dev.cray.com/csm-docker-stable-local:
  tls-verify: true
  images:
    cray-boa:
    - 0.6.19
    cray-bos:
    - 1.6.22
    cray-cfs-operator:
    - 1.10.22
    cray-dhcp-kea:
    - 0.4.22
    cray-dns-unbound:
    - 0.1.19
    cray-product-catalog-update:
    - 0.0.9
    hms-redfish-translation-service:
    - 1.8.7
